name: Build

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-20.04

    env:
      PLUGIN_NAME: github.com/liguangxin/docker-net-dhcp
      PLATFORMS: linux/amd64

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install script dependencies
        run: pip3 install -r scripts/requirements.txt

      - id: vars
        name: Generate build vars
        run: |
          SHA="${{ github.sha }}"
          echo "::set-output name=tag::"${SHA:0:8}-$(date +%s)Z""

      - name: Build
        run: make PLUGIN_TAG=${{ steps.vars.outputs.tag }} multiarch

      - name: Upload artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: /usr/sbin/net-dhcp
        continue-on-error: true
